# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'bcrypt', '~> 3.1', '>= 3.1.16'
gem 'rspec', '~> 3.10'
gem 'minitest', '~> 5.14', '>= 5.14.3'
gem 'byebug', '~> 11.1', '>= 11.1.3'